"""remove unique constraint from permission action

Revision ID: 05924075c978
Revises: 219b020dc51a
Create Date: 2026-07-07 12:36:42.908376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05924075c978'
down_revision: Union[str, Sequence[str], None] = '219b020dc51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=True)
    # ### end Alembic commands ###
