"""SMPT Cnfig

Revision ID: 3f2d533efdf9
Revises: b28f356bad67
Create Date: 2026-07-15 12:28:28.952250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2d533efdf9'
down_revision: Union[str, Sequence[str], None] = 'b28f356bad67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
