"""add project members

Revision ID: 766254bdd392
Revises: 0441dbade295
Create Date: 2026-07-16 12:58:59.321641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766254bdd392'
down_revision: Union[str, Sequence[str], None] = '0441dbade295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_created_by'), 'project_members', ['created_by'], unique=False)
    op.create_index(op.f('ix_project_members_is_deleted'), 'project_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_updated_by'), 'project_members', ['updated_by'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='project_priority'), nullable=False))
    op.add_column('projects', sa.Column('budget', sa.Float(), nullable=False))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DRAFT', 'PLANNING', 'IN_PROGRESS', 'UAT', 'COMPLETED', 'CLOSED', name='project_status'),
               existing_nullable=False)
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('DRAFT', 'PLANNING', 'IN_PROGRESS', 'UAT', 'COMPLETED', 'CLOSED', name='project_status'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_updated_by'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_is_deleted'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_created_by'), table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
