"""Added Reporting Manager Column

Revision ID: 80318186b01b
Revises: 25c2a0e33f56
Create Date: 2026-07-08 11:00:42.042206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80318186b01b'
down_revision: Union[str, Sequence[str], None] = '25c2a0e33f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reporting_manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['reporting_manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'reporting_manager_id')
    # ### end Alembic commands ###
