"""add completed_date to subtasks

Revision ID: 8460693edbd4
Revises: a0aa94cbcffc
Create Date: 2026-07-29 14:26:46.472207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8460693edbd4'
down_revision: Union[str, Sequence[str], None] = 'a0aa94cbcffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheets', 'actual_completion_date')
    op.drop_column('timesheets', 'shared_task_id')
    op.drop_column('timesheets', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('shared_task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('actual_completion_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
