"""Updated schema

Revision ID: 86b994ca2393
Revises: 3a92e459ea70
Create Date: 2026-07-27 16:40:37.577128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b994ca2393'
down_revision: Union[str, Sequence[str], None] = '3a92e459ea70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('subtask_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_timesheets_subtask_id'), 'timesheets', ['subtask_id'], unique=False)
    op.create_foreign_key(None, 'timesheets', 'subtasks', ['subtask_id'], ['id'], ondelete='CASCADE')
    op.drop_column('timesheets', 'subtask')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('subtask', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timesheets', type_='foreignkey')
    op.drop_index(op.f('ix_timesheets_subtask_id'), table_name='timesheets')
    op.drop_column('timesheets', 'subtask_id')
    # ### end Alembic commands ###
