"""add completed_date to subtasks

Revision ID: a0aa94cbcffc
Revises: 86b994ca2393
Create Date: 2026-07-29 14:07:45.310581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0aa94cbcffc'
down_revision: Union[str, Sequence[str], None] = '86b994ca2393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('completed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'completed_date')
    # ### end Alembic commands ###
